### ISSUE TITLE
Project improvements

### ISSUE THREAD

**Issue by raisiqueira** [justapagamentos/justa-angular-library#78]
A list of improvements to this project:

**TODO List**:

- [ ] Update readme
  - [x] main readme
  - [ ] Validators
  - [ ] Mask Directive
  - [ ] Paginator
  - [ ] Add Contributors guide
- [x] Add Prettier
- [ ] ESLint + TypeScript parser instead TSLint
- [x] Add Commit lint (with project scopes)
- [x] Git hooks with Husky
